final List<String> names = [
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
  'Mohamed Ahmed Abdelader',
];
final List<String> grades = [
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
  '45',
];
final List<String> percentage = [
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
  '60%',
];
